### ISSUE TITLE
Client startup crash: out of bounds exception

### ISSUE THREAD

**Issue by Mitchell5200** [Spectre0987/TardisMod#121]
hi im getting a client side crash upon startup after i added it to one of my larger modpacks, i did change the config for the dimensions to prevent the AE conflict and i have tried it with the server files and it seems to launch fine

Modpack ATM3-remix
full log https://pastebin.com/7A6WSNGM

`
java.lang.ArrayIndexOutOfBoundsException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at pl.asie.foamfix.coremod.injections.client.ModelLoaderParallelHelper.bakeParallel(ModelLoaderParallelHelper.java:79)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:108)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 66
	at java.util.LinkedList.toArray(LinkedList.java:1053)
	at java.util.LinkedList.addAll(LinkedList.java:408)
	at java.util.LinkedList.addAll(LinkedList.java:387)
	at java.util.LinkedList.<init>(LinkedList.java:119)
	at forestry.storage.models.ModelCrate.bake(ModelCrate.java:76)
	at pl.asie.foamfix.coremod.injections.client.ModelLoaderParallelHelper.lambda$bakeParallel$0(ModelLoaderParallelHelper.java:83)
	at pl.asie.foamfix.coremod.injections.client.ModelLoaderParallelHelper$$Lambda$3702/902921924.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
`

**Comment by Piehthyte** [comment]
Hey I've gotten the same error because of AE. It happens for my server though and only crashes clients. I think it's on AE's side with how they render everything. Conflicts with the Tardis. I could be wrong but wait for a dev to say right from wrong ;p If I'm not wrong then go report it to AE2 Devs and they will be the ones to fix it.

**Comment by Mitchell5200** [comment]
i thought i had fixed the AE crash by changing the setsDimension config, and it doesn't seem to crash serverside though

**Comment by Spectre0987** [comment]
It's whatever adds foamfix.

**Comment by Spectre0987** [comment]
Going by this crashlog.

**Comment by Mitchell5200** [comment]
after disabling foamfix (and allocating more RAM) the game managed to launch successfully, so i'll go over to the foamfix github and also report there
