### ISSUE TITLE
Crash when shift-right clicking crafting block. -Prospercraft

### ISSUE THREAD

**Issue by bloowalrus272** [Spectre0987/TardisMod#291]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2019-06-24 17:55:12 MDT
Description: Rendering screen

java.lang.NullPointerException
    at net.tardis.mod.client.guis.GuiComponentRepair.drawGuiContainerBackgroundLayer(GuiComponentRepair.java:28)
    at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:75)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1124)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Screen render details --
  Screen name: net.tardis.mod.client.guis.GuiComponentRepair
  Mouse location: Scaled: (332, 221). Absolute: (996, 352)
  Screen size: Scaled: (640, 339). Absolute: (1920, 1017). Scale factor of 3

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['bloowalrus272'/1761887, l='MpServer', x=2056.89, y=129.00, z=2065.54]]
  Chunk stats: MultiplayerChunkCache: 623, 623
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (28,64,252), Chunk: (at 12,4,12 in 1,15; contains blocks 16,0,240 to 31,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 2706638 game time, 2723359 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 19 total; [EntityPlayerSP['bloowalrus272'/1761887, l='MpServer', x=2056.89, y=129.00, z=2065.54], ControlDimChange['Dimensional Control'/401, l='MpServer', x=2056.41, y=128.88, z=2055.75], ControlDirection['Directional Control'/402, l='MpServer', x=2057.09, y=128.78, z=2057.13], ControlDoorSwitch['Door Switch'/403, l='MpServer', x=2056.50, y=128.88, z=2057.19], ControlFastReturn['Fast Return'/404, l='MpServer', x=2056.34, y=129.00, z=2056.96], ControlFuel['Refueller'/405, l='MpServer', x=2055.75, y=128.75, z=2057.13], ControlLandType['Landing Type Selector'/406, l='MpServer', x=2057.22, y=128.88, z=2056.75], ControlLaunch['Time Rotor Handbrake'/407, l='MpServer', x=2056.06, y=129.00, z=2056.97], ControlDoor['Door'/1764237, l='MpServer', x=2042.50, y=129.00, z=2056.50], ControlMag['Coordinate Increment Modifier'/408, l='MpServer', x=2056.06, y=128.88, z=2056.91], ControlPhone['Communicator'/409, l='MpServer', x=2056.50, y=128.94, z=2056.00], ControlRandom['Coordinate Randomizer'/410, l='MpServer', x=2056.50, y=128.94, z=2057.06], ControlStabilizers['Stabilizers'/411, l='MpServer', x=2055.63, y=128.75, z=2056.88], ControlTelepathicCircuts['Telepathic Circuits'/412, l='MpServer', x=2057.13, y=128.88, z=2056.13], ControlX['Space Control - X'/413, l='MpServer', x=2056.00, y=128.97, z=2056.72], ControlY['Space Control - Y'/414, l='MpServer', x=2056.03, y=128.97, z=2056.78], ControlZ['Space Control - Z'/415, l='MpServer', x=2056.06, y=128.97, z=2056.84], ControlWaypoint['Waypoint Selector'/416, l='MpServer', x=2056.58, y=128.84, z=2055.75], ControlSonicSlot['entity.sonic_slot.name'/417, l='MpServer', x=2057.20, y=128.91, z=2056.89]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2066286136 bytes (1970 MB) / 7137656832 bytes (6807 MB) up to 10938744832 bytes (10432 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx11736m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 112 mods loaded, 112 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                        | Version              | Source                                            | Signature                                |
       |:------ |:------------------------- |:-------------------- |:------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                 | 1.12.2               | minecraft.jar                                     | None                                     |
       | LCHIJA | mcp                       | 9.42                 | minecraft.jar                                     | None                                     |
       | LCHIJA | sampler                   | 1.84                 | sampler-1.84.jar                                  | None                                     |
       | LCHIJA | FML                       | 8.0.99.99            | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                     | 14.23.5.2838         | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | creativecoredummy         | 1.0.0                | minecraft.jar                                     | None                                     |
       | LCHIJA | littletilescore           | 1.0.0                | minecraft.jar                                     | None                                     |
       | LCHIJA | OpenEye                   | 0.8                  | OpenEye-1.12.2-0.8.jar                            | None                                     |
       | LCHIJA | moresoundconfigcore       | 1.0.0                | minecraft.jar                                     | None                                     |
       | LCHIJA | randompatches             | 1.12.2-1.16.2.1      | randompatches-1.12.2-1.16.2.1.jar                 | None                                     |
       | LCHIJA | ctm                       | MC1.12.2-0.3.3.22    | CTM-MC1.12.2-0.3.3.22.jar                         | None                                     |
       | LCHIJA | appliedenergistics2       | rv6-stable-6         | appliedenergistics2-rv6-stable-6.jar              | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCHIJA | bdlib                     | 1.14.3.12            | bdlib-1.14.3.12-mc1.12.2.jar                      | None                                     |
       | LCHIJA | ae2stuff                  | 0.7.0.4              | ae2stuff-0.7.0.4-mc1.12.2.jar                     | None                                     |
       | LCHIJA | orbis-lib                 | 0.2.0                | orbis-lib-1.12.2-0.2.0+build79.jar                | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
       | LCHIJA | aether                    | 0.2.2                | aether_ii-1.12.2-0.2.2+build79-universal.jar      | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
       | LCHIJA | mdxlib                    | 3.0.0.15             | mdxlib-3.0.0.15.jar                               | None                                     |
       | LCHIJA | avp                       | 6.0.0.34             | aliensvspredator-6.0.0.34.jar                     | None                                     |
       | LCHIJA | aoa3                      | 3.1.2.b              | AoA3-3.1.2.b.jar                                  | None                                     |
       | LCHIJA | jei                       | 4.15.0.282           | jei_1.12.2-4.15.0.282.jar                         | None                                     |
       | LCHIJA | appleskin                 | 1.0.9                | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
       | LCHIJA | architecturecraft         | @VERSION@            | architecturecraft-1.12-3.80.jar                   | None                                     |
       | LCHIJA | atum                      | 2.0.10               | Atum-1.12.2-2.0.10.jar                            | None                                     |
       | LCHIJA | badwithernocookiereloaded | 1.12.2-3.3.16        | badwithernocookiereloaded-1.12.2-3.3.16.jar       | None                                     |
       | LCHIJA | betterbuilderswands       | 0.13.2               | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar | None                                     |
       | LCHIJA | bettermagnets             | 0.1                  | bettermagnets-mc1.12.x-v1.11.jar                  | None                                     |
       | LCHIJA | betterquesting            | 3.5.300              | BetterQuesting-3.5.300.jar                        | None                                     |
       | LCHIJA | bibliocraft               | 2.4.5                | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
       | LCHIJA | blockmasher               | 1.0                  | BlockMasher_V1.1.jar                              | None                                     |
       | LCHIJA | buildinggadgets           | 2.6.8                | BuildingGadgets-2.6.8.jar                         | None                                     |
       | LCHIJA | chameleon                 | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                          | None                                     |
       | LCHIJA | chisel                    | MC1.12.2-0.2.1.35    | Chisel-MC1.12.2-0.2.1.35.jar                      | None                                     |
       | LCHIJA | chunkpregenerator         | 2.1                  | Chunk Pregenerator V1.12-2.1.jar                  | None                                     |
       | LCHIJA | clockworkphase            | 1.0f                 | ClockworkPhase-1.12.2-1.0f.jar                    | None                                     |
       | LCHIJA | codechickenlib            | 3.2.2.353            | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | fp                        | 26.4.82              | Futurepack-1.12.2-26.4.82.jar                     | a8cfb0576c44b2711002b9e45850732f0b8c7cb6 |
       | LCHIJA | crafttweaker              | 4.1.19               | CraftTweaker2-1.12-4.1.19.jar                     | None                                     |
       | LCHIJA | ctgui                     | 1.0.0                | CraftTweaker2-1.12-4.1.19.jar                     | None                                     |
       | LCHIJA | crafttweakerjei           | 2.0.3                | CraftTweaker2-1.12-4.1.19.jar                     | None                                     |
       | LCHIJA | creativecore              | 1.9.9                | CreativeCore_v1.9.45_mc1.12.2.jar                 | None                                     |
       | LCHIJA | custommainmenu            | 2.0.9                | CustomMainMenu-MC1.12.2-2.0.9.jar                 | None                                     |
       | LCHIJA | dawnoftime                | 0.1                  | dawnoftime-alpha-1.0.2.jar                        | None                                     |
       | LCHIJA | ptrmodellib               | 1.0.4                | PTRLib-1.0.4.jar                                  | None                                     |
       | LCHIJA | props                     | 2.6.2                | Decocraft-2.6.2_1.12.2.jar                        | None                                     |
       | LCHIJA | journeymap                | 1.12.2-5.5.5b7       | journeymap-1.12.2-5.5.5b7.jar                     | None                                     |
       | LCHIJA | defaultoptions            | 9.2.8                | DefaultOptions_1.12.2-9.2.8.jar                   | None                                     |
       | LCHIJA | demagnetize               | 1.12.2-1.0.1         | demagnetize-1.12.2-1.0.1.jar                      | None                                     |
       | LCHIJA | eleccore                  | 1.9.452              | ElecCore-1.12.2-1.9.452.jar                       | None                                     |
       | LCHIJA | elevatorid                | 1.4.2                | ElevatorMod-1.12.2-1.4.2.jar                      | None                                     |
       | LCHIJA | csb_ench_table            | 1.1.3                | EnchantingTable-1.12-1.1.3.jar                    | None                                     |
       | LCHIJA | shetiphiancore            | 3.5.9                | shetiphiancore-1.12.0-3.5.9.jar                   | None                                     |
       | LCHIJA | endertanks                | 1.6.8                | endertanks-1.12.0-1.6.8.jar                       | None                                     |
       | LCHIJA | engineersdecor            | 1.0.9-b1             | engineersdecor-1.12.2-1.0.9-b1.jar                | ed58ed655893ced6280650866985abcae2bf7559 |
       | LCHIJA | erebus                    | 1.0.30               | Erebus-1.0.30.jar                                 | None                                     |
       | LCHIJA | fastleafdecay             | v14                  | FastLeafDecay-v14.jar                             | None                                     |
       | LCHIJA | fp.api                    | 1.1.0                | Futurepack-1.12.2-26.4.82.jar                     | None                                     |
       | LCHIJA | gaiadimension             | 1.0.5                | gaiadimension-1.12.2-1.0.5.jar                    | None                                     |
       | LCHIJA | glacidus                  | 1.2.1                | Glacidus-1.12.2-v1.2.1.jar                        | None                                     |
       | LCHIJA | gregtech                  | 1.8.3.418            | gregtech-1.12.2-1.8.3.418.jar                     | None                                     |
       | LCHIJA | railcraft                 | 12.0.0               | railcraft-12.0.0.jar                              | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LCHIJA | theoneprobe               | 1.4.28               | theoneprobe-1.12-1.4.28.jar                       | None                                     |
       | LCHIJA | twilightforest            | 3.9.888              | twilightforest-1.12.2-3.9.888-universal.jar       | None                                     |
       | LCHIJA | immersiveengineering      | 0.12-89              | ImmersiveEngineering-0.12-89.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | LCHIJA | immersivepetroleum        | 1.1.9                | immersivepetroleum-1.12.2-1.1.9.jar               | None                                     |
       | LCHIJA | inventorytweaks           | 1.64+dev.146.2180b27 | InventoryTweaks-1.64+dev.146.jar                  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | ironbackpacks             | 1.12.2-3.0.8-12      | IronBackpacks-1.12.2-3.0.8-12.jar                 | None                                     |
       | LCHIJA | keywizard                 | 1.12.2-1.7           | keywizard-1.12.2-1.7.jar                          | None                                     |
       | LCHIJA | labyrinth                 | ${version}           | Labyrinth-1.12.2-1.0.jar                          | None                                     |
       | LCHIJA | landlust                  | 1.12.2-0.3.6         | landlust-1.12.2-0.3.6.jar                         | None                                     |
       | LCHIJA | littletiles               | 1.5.0                | LittleTiles_v1.5.0-pre135_mc1.12.2.jar            | None                                     |
       | LCHIJA | lostcities                | 2.0.20               | lostcities-1.12-2.0.20.jar                        | None                                     |
       | LCHIJA | lostsouls                 | 1.1.4                | lostsouls-1.12-1.1.4.jar                          | None                                     |
       | LCHIJA | mcjtylib_ng               | 3.5.3                | mcjtylib-1.12-3.5.3.jar                           | None                                     |
       | LCHIJA | testdummy                 | 1.12                 | MmmMmmMmmMmm-1.12-1.14.jar                        | None                                     |
       | LCHIJA | modnametooltip            | 1.10.0               | modnametooltip_1.12.2-1.10.0.jar                  | None                                     |
       | LCHIJA | numina                    | 1.12.2-1.0.38        | Numina-1.12.2-1.0.38.jar                          | None                                     |
       | LCHIJA | powersuits                | 1.12.2-1.0.41        | ModularPowersuits-1.12.2-1.0.41.jar               | None                                     |
       | LCHIJA | moolands                  | 1.12.2-1.1.5         | moolands-1.12.2-1.1.5.jar                         | None                                     |
       | LCHIJA | moreoverlays              | 1.14                 | moreoverlays-1.14-mc1.12.2.jar                    | None                                     |
       | LCHIJA | morpheus                  | 1.12.2-3.5.106       | Morpheus-1.12.2-3.5.106.jar                       | None                                     |
       | LCHIJA | mousetweaks               | 2.10                 | MouseTweaks-2.10-mc1.12.2.jar                     | None                                     |
       | LCHIJA | multibeds                 | 1.4.4                | multibeds-1.12.0-1.4.4.jar                        | None                                     |
       | LCHIJA | multistorage              | 1.4.14               | multistorage-1.12.0-1.4.14.jar                    | None                                     |
       | LCHIJA | nonausea                  | 1.0                  | NoNausea-MC1.12-1.0.jar                           | None                                     |
       | LCHIJA | norecipebook              | 1.2.1                | noRecipeBook_v1.2.2formc1.12.2.jar                | None                                     |
       | LCHIJA | neid                      | 1.5.4.4              | NotEnoughIDs-1.5.4.4.jar                          | None                                     |
       | LCHIJA | patchouli                 | 1.0-19               | Patchouli-1.0-19.jar                              | None                                     |
       | LCHIJA | placebo                   | 1.6.0                | Placebo-1.12.2-1.6.0.jar                          | None                                     |
       | LCHIJA | questbook                 | 3.1.EXP_NET2-1.12    | questbook-3.1.EXP_NET2-1.12.jar                   | None                                     |
       | LCHIJA | tardis                    | 0.1.0D               | tardis-0.1.0D.jar                                 | None                                     |
       | LCHIJA | regeneration              | 1.6.6                | Regeneration-1.12.2-1.6.6.jar                     | None                                     |
       | LCHIJA | resourceloader            | 1.5.3                | ResourceLoader-MC1.12.1-1.5.3.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | sgcraft                   | 1.13.2               | SGCraft-2.0.1.jar                                 | None                                     |
       | LCHIJA | bq_standard               | 3.4.159              | StandardExpansion-3.4.159.jar                     | None                                     |
       | LCHIJA | storagedrawers            | 1.12-5.3.5           | StorageDrawers-1.12.2-5.3.8.jar                   | None                                     |
       | LCHIJA | supersoundmuffler         | 1.0.2.10             | supersoundmuffler-1.12.2-1.0.2.10.jar             | None                                     |
       | LCHIJA | toastcontrol              | 1.8.1                | Toast Control-1.12.2-1.8.1.jar                    | None                                     |
       | LCHIJA | tombstone                 | 3.5.4                | tombstone-3.5.4-1.12.jar                          | None                                     |
       | LCHIJA | torchmaster               | 1.7.1.74             | torchmaster_1.12.2-1.7.1.74.jar                   | 5e9a436b366831c8f54a7e80b015784da69278c6 |
       | LCHIJA | tropicraft                | 7.1.9.115            | tropicraft-MC1.12.2-7.1.9.115.jar                 | None                                     |
       | LCHIJA | vanillafix                | 1.0.10-SNAPSHOT      | VanillaFix-1.0.10-99.jar                          | None                                     |
       | LCHIJA | worldstripper             | 1.6.0-1.12.2         | World-Stripper-1.6.0-1.12.2.jar                   | None                                     |
       | LCHIJA | xtones                    | 1.12-1.0.8-11        | Xtones-1.12-1.0.8-11.jar                          | None                                     |
       | LCHIJA | zettaindustries           | 1.3                  | zettaindustries-1.3-1.12.2-161.jar                | None                                     |
       | LCHIJA | phosphor-lighting         | 1.12.2-0.2.4         | phosphor-1.12.2-0.2.4+build46-universal.jar       | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | k9                        | 1.12.2-1.3.1.2       | k9-1.12.2-1.3.1.2.jar                             | None                                     |
       | LCHIJA | moresoundconfig           | 1.0.4                | moresoundconfig-1.0.4.jar                         | 7904c4e13947c8a616c5f39b26bdeba796500722 |
       | LCHIJA | reauth                    | 3.6.0                | reauth-3.6.0.jar                                  | daba0ec4df71b6da841768c49fb873def208a1e3 |
       | LCHIJA | thebetweenlands           | 3.4.9                | TheBetweenlands-3.4.9-universal.jar               | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | LCHIJA | midnight                  | 0.3.5                | themidnight-0.3.5.jar                             | None                                     |
       | LCHIJA | weeping-angels            | 1.12.2-37            | weeping-angels-37.jar                             | None                                     |
       | LCHIJA | eleccoreloader            | 1.9.452              | ElecCore-1.12.2-1.9.452.jar                       | None                                     |
  Loaded coremods (and transformers): SplashAnimationCoremod (SplashAnimation-0.2.1.jar)
                                        pl.asie.splashanimation.core.SplashProgressTransformer
                                      LittlePatchingLoader (LittleTiles_v1.5.0-pre135_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      OpenEyePlugin (OpenEye-1.12.2-0.8.jar)
                                        openeye.asm.MultiTransformer
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.9-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      CreativePatchingLoader (CreativeCore_v1.9.45_mc1.12.2.jar)
                                        
                                      FMLModule (mdxlib-3.0.0.15.jar)
                                        com.asx.mdx.AccessTransformer
                                      midnight (themidnight-0.3.5.jar)
                                        com.mushroom.midnight.core.transformer.MidnightClassTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      MoreSoundConfigCore (moresoundconfig-core-1.0.4.jar)
                                        ichttt.mods.moresoundconfig.asm.MSCTransformer
                                      Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
                                        com.chocohead.biab.BornInABarn
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      Plugin (NotEnoughIDs-1.5.4.4.jar)
                                        ru.fewizz.neid.asm.Transformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46-universal.jar)
                                        
                                      ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
                                        shetiphian.asm.ClassTransformer
                                      Regeneration Sound Handler (Regeneration-1.12.2-1.6.6.jar)
                                        me.swirtzly.regeneration.asm.RegenClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      RandomPatches (randompatches-1.12.2-1.16.2.1.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      LoadingPlugin (NoNausea-MC1.12-1.0.jar)
                                        lumien.nonausea.asm.ClassTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GTX 970M/PCIe/SSE2'
  AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
  List of loaded APIs: * appliedenergistics2|API (rv6) from appliedenergistics2-rv6-stable-6.jar
                       * AtumAPI (0.0.2) from Atum-1.12.2-2.0.10.jar
                       * AVPAPI (1.0.0) from aliensvspredator-6.0.0.34.jar
                       * BetterQuesting|API (3.2) from BetterQuesting-3.5.300.jar
                       * BetterQuesting|API2 (3.1) from BetterQuesting-3.5.300.jar
                       * BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar
                       * BetweenlandsAPI (1.12.2) from TheBetweenlands-3.4.9-universal.jar
                       * Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
                       * ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
                       * CSLib|API (1.0.1) from PTRLib-1.0.4.jar
                       * ctm-api (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
                       * ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
                       * ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
                       * ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
                       * ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
                       * ElecCoreAPI (1.0.0) from ElecCore-1.12.2-1.9.452.jar
                       * ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-89.jar
                       * ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-89.jar
                       * journeymap|client-api (1.4) from journeymap-1.12.2-5.5.5b7.jar
                       * journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.5b7.jar
                       * journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.5b7.jar
                       * journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.5b7.jar
                       * journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.5b7.jar
                       * JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.15.0.282.jar
                       * MouseTweaks|API (1.0) from MouseTweaks-2.10-mc1.12.2.jar
                       * PatchouliAPI (6) from Patchouli-1.0-19.jar
                       * railcraft:api_carts (3.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_charge (4.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_core (3.2.0) from railcraft-12.0.0.jar
                       * railcraft:api_crafting (4.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_events (2.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_fuel (2.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_helpers (2.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_items (2.4.0) from railcraft-12.0.0.jar
                       * railcraft:api_signals (4.0.0) from railcraft-12.0.0.jar
                       * railcraft:api_tracks (5.1.1) from railcraft-12.0.0.jar
                       * StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
                       * StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
                       * StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
                       * StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
                       * StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
                       * StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
                       * Thaumcraft|API (6.0.2) from railcraft-12.0.0.jar
                       * theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.28.jar
                       * tombstone-api (1.0.2) from tombstone-3.5.4-1.12.jar
                       * tombstone-api-capability (1.0.2) from tombstone-3.5.4-1.12.jar
                       * tombstone-api-event (1.0.2) from tombstone-3.5.4-1.12.jar
                       * tombstone-api-magic (1.0.2) from tombstone-3.5.4-1.12.jar
                       * tombstone-api-recipe (1.0.2) from tombstone-3.5.4-1.12.jar
  AE2 Integration: IC2:OFF, RC:ON, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:ON
  Suspected Mods: TARDIS Mod (tardis)
  Launched Version: forge-14.23.5.2838
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 970M/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: No
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by bloowalrus272** [comment]
Wrong format.
