### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by JHughes89** [Spectre0987/TardisMod#303]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 12/07/19 16:35
Description: Ticking block entity

java.lang.NoClassDefFoundError: net/tardis/mod/client/EnumExterior
	at net.tardis.mod.common.entities.EntityTardis.func_70088_a(EntityTardis.java:34)
	at net.minecraft.entity.Entity.<init>(Entity.java:217)
	at net.tardis.mod.common.entities.EntityTardis.<init>(EntityTardis.java:29)
	at net.tardis.mod.common.tileentity.TileEntityDoor.func_73660_a(TileEntityDoor.java:202)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.tardis.mod.client.EnumExterior
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 11 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@50b1f030 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 13 more
Caused by: java.lang.RuntimeException: Attempted to load class net/tardis/mod/client/EnumExterior for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.tardis.mod.common.entities.EntityTardis.func_70088_a(EntityTardis.java:34)
	at net.minecraft.entity.Entity.<init>(Entity.java:217)
	at net.tardis.mod.common.entities.EntityTardis.<init>(EntityTardis.java:29)
	at net.tardis.mod.common.tileentity.TileEntityDoor.func_73660_a(TileEntityDoor.java:202)

-- Block entity being ticked --
Details:
	Name: tardis:tileentitydoor03 // net.tardis.mod.common.tileentity.exteriors.TileEntityDoor03
	Block type: ID #333 (tile.tardis.tardis_top_02 // net.tardis.mod.common.blocks.BlockTardisTop // tardis:tardis_top_02)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (501,38,976), Chunk: (at 5,2,0 in 31,61; contains blocks 496,0,976 to 511,255,991), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Actual block type: ID #333 (tile.tardis.tardis_top_02 // net.tardis.mod.common.blocks.BlockTardisTop // tardis:tardis_top_02)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['JHughes89'/59, l='world', x=504.66, y=39.00, z=983.64]]
	Chunk stats: ServerChunkCache: 697 Drop: 0
	Level seed: -6700658489678255160
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-180,64,256), Chunk: (at 12,4,0 in -12,16; contains blocks -192,0,256 to -177,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 153518 game time, 42898 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 94218 (now: false), thunder time: 14112 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 341006480 bytes (325 MB) / 541589504 bytes (516 MB) up to 1430257664 bytes (1364 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID            | Version      | Source                                  | Signature                                |
	|:------ |:------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft     | 1.12.2       | minecraft.jar                           | None                                     |
	| LCHIJA | mcp           | 9.42         | minecraft.jar                           | None                                     |
	| LCHIJA | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2838-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge         | 14.23.5.2838 | forge-1.12.2-14.23.5.2838-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | jei           | 4.13.1.225   | jei_1.12.2-4.13.1.225.jar               | None                                     |
	| LCHIJA | journeymap    | 1.12.2-5.5.4 | journeymap-1.12.2-5.5.4.jar             | None                                     |
	| LCHIJA | tardis        | 0.1.0E       | tardis-0.1.0E.jar                       | None                                     |
	| LCHIJA | bspkrscore    | at_0.9       | TreeCapitator-Mod-1.12.jar              | None                                     |
	| LCHIJA | treecapitator | at_0.9       | TreeCapitator-Mod-1.12.jar              | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['JHughes89'/59, l='world', x=504.66, y=39.00, z=983.64]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Spectre0987** [comment]
Update to the latest
