### ISSUE TITLE
game crash when rendering open doors in Mystcraft dimension

### ISSUE THREAD

**Issue by brandonmack111** [Spectre0987/TardisMod#334]
When the doors are open inside a Mystcraft dimension, the game crashes. Looking at the crash report, it seems to confirm that the problem is caused by trying to render the door from within that dimension.

This issue occurs on both the inside and outside of the TARDIS (had to move my player out of the TARDIS dimension with NBTExplorer, or the game crashes on load)

Here's the crash log:

 

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
>   Quark Plugin (Quark-r1.6-177.jar)
>   CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
>   OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
>   EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
>   LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
> Contact their authors BEFORE contacting forge
> 
> // Would you like a cupcake?
> 
> Time: 5/3/20 2:08 PM
> Description: Rendering entity in world
> 
> java.lang.NullPointerException: Rendering entity in world
> 	at com.xcompwiz.mystcraft.world.WorldProviderMyst.func_76562_b(WorldProviderMyst.java:138)
> 	at net.tardis.mod.util.client.RenderHelper.renderPortal(RenderHelper.java:80)
> 	at net.tardis.mod.util.client.RenderHelper.renderPortal(RenderHelper.java:136)
> 	at net.tardis.mod.client.renderers.controls.RenderDoor.doRender(RenderDoor.java:68)
> 	at net.tardis.mod.client.renderers.controls.RenderDoor.func_76986_a(RenderDoor.java:22)
> 	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
> 	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
> 	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:849)
> 	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1928)
> 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
> 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at com.xcompwiz.mystcraft.world.WorldProviderMyst.func_76562_b(WorldProviderMyst.java:138)
> 	at net.tardis.mod.util.client.RenderHelper.renderPortal(RenderHelper.java:80)
> 	at net.tardis.mod.util.client.RenderHelper.renderPortal(RenderHelper.java:136)
> 	at net.tardis.mod.client.renderers.controls.RenderDoor.doRender(RenderDoor.java:68)
> 	at net.tardis.mod.client.renderers.controls.RenderDoor.func_76986_a(RenderDoor.java:22)
> 
> -- Entity being rendered --
> Details:
> 	Entity Type: tardis:tardis_door (net.tardis.mod.common.entities.controls.ControlDoor)
> 	Entity ID: 335
> 	Entity Name: Door
> 	Entity's Exact location: 250.50, 129.00, 264.50
> 	Entity's Block location: World: (250,129,264), Chunk: (at 10,8,8 in 15,16; contains blocks 240,0,256 to 255,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
> 	Entity's Momentum: 0.00, 0.00, 0.00
> 	Entity's Passengers: []
> 	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
> 
> -- Renderer details --
> Details:
> 	Assigned renderer: net.tardis.mod.client.renderers.controls.RenderDoor@49bbb1c3
> 	Location: -13.66,1.00,1.23 - World: (-14,1,1), Chunk: (at 2,0,1 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Rotation: -90.0
> 	Delta: 0.22002792
> Stacktrace:
> 	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
> 	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
> 	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:849)
> 	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1928)
> 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
> 
> -- Affected level --
> Details:
> 	Level name: MpServer
> 	All players: 0 total; []
> 	Chunk stats: MultiplayerChunkCache: 0, 0
> 	Level seed: -4934676238107849831
> 	Level generator: ID 00 - default, ver 1. Features enabled: false
> 	Level generator options: 
> 	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
> 	Level time: 0 game time, 0 day time
> 	Level dimension: 0
> 	Level storage version: 0x00000 - Unknown?
> 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> 	Level game mode: ~~ERROR~~ NullPointerException: null
> 	Forced entities: 0 total; []
> 	Retry entities: 0 total; []
> 	Server brand: fml,forge
> 	Server type: Integrated singleplayer server
> Stacktrace:
> 	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
> 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Windows 7 (amd64) version 6.1
> 	Java Version: 1.8.0_51, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 1490598696 bytes (1421 MB) / 4227858432 bytes (4032 MB) up to 4294967296 bytes (4096 MB)
> 	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
> 	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 94 mods loaded, 94 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State  | ID                                | Version           | Source                                        | Signature                                |
> 	|:------ |:--------------------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
> 	| LCHIJA | minecraft                         | 1.12.2            | minecraft.jar                                 | None                                     |
> 	| LCHIJA | mcp                               | 9.42              | minecraft.jar                                 | None                                     |
> 	| LCHIJA | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
> 	| LCHIJA | forge                             | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
> 	| LCHIJA | openmodscore                      | 0.12.2            | minecraft.jar                                 | None                                     |
> 	| LCHIJA | opencomputers|core                | 1.7.5.192         | minecraft.jar                                 | None                                     |
> 	| LCHIJA | aiimprovements                    | 0.0.1.3           | AIImprovements-1.12-0.0.1b3.jar               | None                                     |
> 	| LCHIJA | jei                               | 4.15.0.293        | jei_1.12.2-4.15.0.293.jar                     | None                                     |
> 	| LCHIJA | quark                             | r1.6-177          | Quark-r1.6-177.jar                            | None                                     |
> 	| LCHIJA | autoreglib                        | 1.3-32            | AutoRegLib-1.3-32.jar                         | None                                     |
> 	| LCHIJA | blockcraftery                     | 1.12.2-1.3.1      | blockcraftery-1.12.2-1.3.1.jar                | None                                     |
> 	| LCHIJA | buildinggadgets                   | 2.7.3             | BuildingGadgets-2.7.3.jar                     | None                                     |
> 	| LCHIJA | ctm                               | MC1.12.2-1.0.1.30 | CTM-MC1.12.2-1.0.1.30.jar                     | None                                     |
> 	| LCHIJA | chisel                            | MC1.12.2-1.0.1.44 | Chisel-MC1.12.2-1.0.1.44.jar                  | None                                     |
> 	| LCHIJA | cathedral                         | 1.12.2-1.9.9      | Cathedral-1.12.2-1.9.9.jar                    | None                                     |
> 	| LCHIJA | chameleon                         | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                      | None                                     |
> 	| LCHIJA | chunkanimator                     | 1.2               | ChunkAnimator-MC1.12-1.2.jar                  | None                                     |
> 	| LCHIJA | clumps                            | 3.1.2             | Clumps-3.1.2.jar                              | None                                     |
> 	| LCHIJA | codechickenlib                    | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
> 	| LCHIJA | cyclopscore                       | 1.6.2             | CyclopsCore-1.12.2-1.6.2.jar                  | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
> 	| LCHIJA | commoncapabilities                | 2.4.5             | CommonCapabilities-1.12.2-2.4.5.jar           | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
> 	| LCHIJA | compactmachines3                  | 3.0.18            | compactmachines3-1.12.2-3.0.18-b278.jar       | None                                     |
> 	| LCHIJA | craftstudioapi                    | 1.0.0             | CraftStudio-1.0.0.93-mc1.12-alpha.jar         | None                                     |
> 	| LCHIJA | customizeddungeonloot             | 1.0.3             | Customized-Dungeon-Loot-1.12+-(v.1.0.3).jar   | None                                     |
> 	| LCHIJA | waila                             | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
> 	| LCHIJA | endercore                         | 1.12.2-0.5.73     | EnderCore-1.12.2-0.5.73.jar                   | None                                     |
> 	| LCHIJA | enderio                           | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
> 	| LCHIJA | p455w0rdslib                      | 2.3.161           | p455w0rdslib-1.12.2-2.3.161.jar               | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
> 	| LCHIJA | danknull                          | 1.7.89            | DankNull-1.12.2-1.7.89.jar                    | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
> 	| LCHIJA | debark                            | 0.1.2             | Debark-0.1.2.jar                              | None                                     |
> 	| LCHIJA | dimdoors                          | 3.0.9+287         | DimensionalDoors-3.0.9-287.jar                | None                                     |
> 	| LCHIJA | enderiointegrationtic             | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
> 	| LCHIJA | enderiobase                       | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
> 	| LCHIJA | enderioconduits                   | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
> 	| LCHIJA | enderioconduitsappliedenergistics | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
> 	| LCHIJA | opencomputers                     | 1.7.5.192         | OpenComputers-MC1.12.2-1.7.5.192.jar          | None                                     |
> 	| LCHIJA | enderioconduitsopencomputers      | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
> 	| LCHIJA | enderioconduitsrefinedstorage     | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
> 	| LCHIJA | enderiointegrationforestry        | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
> 	| LCHIJA | enderiointegrationticlate         | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
> 	| LCHIJA | enderiomachines                   | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
> 	| LCHIJA | enderiopowertools                 | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                     | None                                     |
> 	| LCHIJA | enderstorage                      | 2.4.6.137         | EnderStorage-1.12.2-2.4.6.137-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
> 	| LCHIJA | zerocore                          | 1.12.2-0.1.2.8    | zerocore-1.12.2-0.1.2.8.jar                   | None                                     |
> 	| LCHIJA | bigreactors                       | 1.12.2-0.4.5.67   | ExtremeReactors-1.12.2-0.4.5.67.jar           | None                                     |
> 	| LCHIJA | felling                           | 1.4.1             | felling-1.4.1-1.12.x.jar                      | None                                     |
> 	| LCHIJA | forgemultipartcbe                 | 2.6.2.83          | ForgeMultipart-1.12.2-2.6.2.83-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
> 	| LCHIJA | microblockcbe                     | 2.6.2.83          | ForgeMultipart-1.12.2-2.6.2.83-universal.jar  | None                                     |
> 	| LCHIJA | minecraftmultipartcbe             | 2.6.2.83          | ForgeMultipart-1.12.2-2.6.2.83-universal.jar  | None                                     |
> 	| LCHIJA | guideapi                          | 1.12-2.1.8-63     | Guide-API-1.12-2.1.8-63.jar                   | None                                     |
> 	| LCHIJA | tardis                            | 0.1.2             | tardis-0.1.2.jar                              | None                                     |
> 	| LCHIJA | handles                           | 1.12.2-1.5.2.0    | handles-1.12.2-1.6.1.0.jar                    | None                                     |
> 	| LCHIJA | integrateddynamics                | 1.1.2             | IntegratedDynamics-1.12.2-1.1.2.jar           | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
> 	| LCHIJA | integratedcrafting                | 1.0.9             | IntegratedCrafting-1.12.2-1.0.9.jar           | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
> 	| LCHIJA | integrateddynamicscompat          | 1.0.0             | IntegratedDynamics-1.12.2-1.1.2.jar           | None                                     |
> 	| LCHIJA | integratedterminals               | 1.0.13            | IntegratedTerminals-1.12.2-1.0.13.jar         | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
> 	| LCHIJA | integratedterminalscompat         | 1.0.0             | IntegratedTerminals-1.12.2-1.0.13.jar         | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
> 	| LCHIJA | integratedtunnels                 | 1.6.11            | IntegratedTunnels-1.12.2-1.6.11.jar           | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
> 	| LCHIJA | integratedtunnelscompat           | 1.0.0             | IntegratedTunnels-1.12.2-1.6.11.jar           | None                                     |
> 	| LCHIJA | journeymap                        | 1.12.2-5.5.9      | journeymap-1.12.2-5.5.9.jar                   | None                                     |
> 	| LCHIJA | lightingwand                      | 1.0.4             | LightingWand-1.0.4.jar                        | None                                     |
> 	| LCHIJA | mcjtylib_ng                       | 3.5.4             | mcjtylib-1.12-3.5.4.jar                       | None                                     |
> 	| LCHIJA | modernlamps                       | 1.0.3             | ModernLights-1.0.3_1.12.jar                   | None                                     |
> 	| LCHIJA | numina                            | 1.12.2-1.0.38     | Numina-1.12.2-1.0.38.jar                      | None                                     |
> 	| LCHIJA | powersuits                        | 1.12.2-1.0.46     | ModularPowersuits-1.12.2-1.0.46.jar           | None                                     |
> 	| LCHIJA | mystcraft                         | 0.13.7.04         | mystcraft-1.12.2-0.13.7.04.jar                | None                                     |
> 	| LCHIJA | moremystcraft                     | 0.8.5             | moremystcraft-1.12.2-0.8.5.jar                | None                                     |
> 	| LCHIJA | mystcraft_info                    | 1.0.3.0           | mystcraft_info-1.12.2-1.0.5.0.jar             | None                                     |
> 	| LCHIJA | recipehandler                     | 0.13              | NoMoreRecipeConflict-0.13(1.12.2).jar         | None                                     |
> 	| LCHIJA | openmods                          | 0.12.2            | OpenModsLib-1.12.2-0.12.2.jar                 | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
> 	| LCHIJA | openblocks                        | 1.8.1             | OpenBlocks-1.12.2-1.8.1.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
> 	| LCHIJA | pages                             | 1.3.3             | pages-1.12.2-1.3.3.jar                        | None                                     |
> 	| LCHIJA | placeableitems                    | 3.3               | placeableitems-3.3.jar                        | None                                     |
> 	| LCHIJA | portablecraft                     | 1.1               | portablecraft-1.1.jar                         | None                                     |
> 	| LCHIJA | prefab                            | 1.3.0.26          | prefab-1.3.0.26.jar                           | None                                     |
> 	| LCHIJA | psi                               | r1.1-77           | Psi-r1.1-77.jar                               | None                                     |
> 	| LCHIJA | selim_enchants                    | 2.1.1             | Selim's+Enchantments-1.12.2-2.1.1.jar         | None                                     |
> 	| LCHIJA | storagenetwork                    | 1.7.10            | SimpleStorageNetwork-1.12.2-1.7.10.jar        | None                                     |
> 	| LCHIJA | simply_trash                      | 1.0.0             | SimplyTrash-1.12.2-V1.0.0.jar                 | None                                     |
> 	| LCHIJA | storagedrawers                    | 1.12.2-5.4.0      | StorageDrawers-1.12.2-5.4.0.jar               | None                                     |
> 	| LCHIJA | subterraneanswitcheroo            | 1.1.0             | SubSwitch1.1.0.jar                            | None                                     |
> 	| LCHIJA | tektopia                          | 1.1.0             | tektopia-1.1.0.jar                            | None                                     |
> 	| LCHIJA | tektopiainformation               | 1.4.0             | TektopiaInformation-1.12.2-1.1.0-1.4.0.jar    | None                                     |
> 	| LCHIJA | tetra                             | 0.39.1            | tetra-1.12.2-0.39.1.jar                       | None                                     |
> 	| LCHIJA | undergroundbiomes                 | 1.3.7             | UndergroundBiomesConstructs-1.12-1.3.7.jar    | None                                     |
> 	| LCHIJA | universalremote                   | 1.12-0.9.10       | UniversalRemote-1.12-0.9.10.jar               | None                                     |
> 	| LCHIJA | unlimitedchiselworks              | 0.3.4             | UnlimitedChiselWorks-0.3.4.jar                | None                                     |
> 	| LCHIJA | veining                           | 1.3.2             | veining-1.3.2-1.12.x.jar                      | None                                     |
> 	| LCHIJA | wallpapercraft                    | 1.0.1-alpha       | wallpapercraft_1.12.2-1.0.2-beta.jar          | None                                     |
> 	| LCHIJA | wards                             | 1.3.1             | wards-1.3.1.jar                               | None                                     |
> 	| LCHIJA | woot                              | 1.12.2-1.4.11     | woot-1.12.2-1.4.11.jar                        | None                                     |
> 	| LCHIJA | xnet                              | 1.8.2             | xnet-1.12-1.8.2.jar                           | None                                     |
> 	| LCHIJA | ynot                              | 0.2.4             | YNot-0.2.4.jar                                | None                                     |
> 	| LCHIJA | mysticallib                       | 1.12.2-1.6.0      | mysticallib-1.12.2-1.6.0.jar                  | None                                     |
> 
> 	Loaded coremods (and transformers): 
> TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
>   li.cil.oc.common.asm.ClassTransformer
> Quark Plugin (Quark-r1.6-177.jar)
>   vazkii.quark.base.asm.ClassTransformer
> CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
>   team.chisel.ctm.client.asm.CTMTransformer
> OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
>   openmods.core.OpenModsClassTransformer
> EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
>   com.enderio.core.common.transform.EnderCoreTransformer
>   com.enderio.core.common.transform.SimpleMixinPatcher
> LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
>   lumien.chunkanimator.asm.ClassTransformer
> 	GL info: ' Vendor: 'Intel' Version: '3.0.0 - Build 8.15.10.2291' Renderer: 'Intel(R) HD Graphics Family'
> 	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
> 	[Psi] Active spell: None
> 	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
>                   * Optifine is installed. This is NOT supported.
>                  This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
> 
> 	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 	!!!You are looking at the diagnostics information, not at the crash.       !!!
> 	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
> 	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> 	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
> 	LWJGL: 2.9.4
> 	OpenGL: Intel(R) HD Graphics Family GL version 3.0.0 - Build 8.15.10.2291, Intel
> 	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
> Using GL 1.3 multitexturing.
> Using GL 1.3 texture combiners.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Shaders are available because OpenGL 2.1 is supported.
> VBOs are available because OpenGL 1.5 is supported.
> 
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'
> 	Type: Client (map_client.txt)
> 	Resource Packs: 
> 	Current Language: English (US)
> 	Profiler Position: N/A (disabled)
> 	CPU: 4x Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz
> 	OptiFine Version: OptiFine_1.12.2_HD_U_F5
> 	OptiFine Build: 20191204-141934
> 	Render Distance Chunks: 8
> 	Mipmaps: 4
> 	Anisotropic Filtering: 1
> 	Antialiasing: 0
> 	Multitexture: false
> 	Shaders: null
> 	OpenGlVersion: 3.0.0 - Build 8.15.10.2291
> 	OpenGlRenderer: Intel(R) HD Graphics Family
> 	OpenGlVendor: Intel
> 	CpuCount: 4

**Comment by brandonmack111** [comment]
Turning off BOTI does resolve the crash issue - which at least makes the game playable, and again confirms the problem.

**Comment by josh-65** [comment]
You could try going to the config and then scroll to the bottom where it should say something like disable rendering mod block. Then put mystcraft:* on a new line in-between the arrows.

**Comment by PaulJFleming** [comment]
I realise this is a while later, but I have experienced the same issue with running sgcraft alongside Tardismod. 
Every time I turned to look "out of the doors" the game crashed out - with that fluidblockrender issue in the crash log.

Lots of tea drinking and research later, I resorted to poke and hope!
In the end, I loaded up optifine - OptiFine_1.12.2_HD_U_F5 - and got the huge warning on startup  about BOTI problems and optifine, but now the game does not crash out and I have both mods loaded and BOTI active.

More of a sticking plaster than a proper fix, but if it makes it work?
Hope this helps.

Paul.
